// lib/projectsSEO.ts
export const listItems = [
  {
    slug: 'Installation-electrique',
    image: "/images/installation-electrique-neuve.webp",
    title: "Installation électrique complète à Cannes",
    subtitle: "Appartements et villas électriques à Cannes",
    description: `Nous avons réalisé une installation électrique complète dans une villa neuve située dans les hauteurs de Cannes. Ce chantier électrique à Cannes a inclus la pose de câblage général, l’installation d’un tableau électrique avec disjoncteurs différenciels certifiés, ainsi que l’intégration soignée de prises, interrupteurs et éclairages dans chaque pièce. Notre savoir-faire garantit un confort optimal, une sécurité renforcée, et une conformité totale aux normes NF C 15-100 en vigueur dans la région de Cannes. Nous avons également conseillé notre client sur des solutions d’économie d’énergie innovantes adaptées aux logements cannois, afin de réduire la consommation électrique tout en améliorant la performance énergétique.`,
    client: "Marc Dupuis",
    price: "1 590 €",
    category: "Installation électrique",
    date: "12 janvier 2024",
    location: "Quartier Mougins, Cannes",
  },
  {
    slug: 'Remise-aux-normes',
    image: "/images/norme-electrique.webp",
    title: "Remise aux normes électrique NF C 15-100 à Cannes",
    subtitle: "Sécurisation et conformité électrique au centre-ville de Cannes",
    description: `Dans un appartement ancien du centre-ville de Cannes, notre équipe a effectué une remise aux normes électrique complète conforme à la norme NF C 15-100. Nous avons remplacé le tableau électrique obsolète, réorganisé les circuits électriques défectueux, et ajouté des protections différentielles modernes. Ce projet de mise aux normes électriques à Cannes a été réalisé avec un minimum de gêne pour les occupants grâce à une planification rigoureuse. Cette remise aux normes garantit aujourd’hui la sécurité maximale des habitants et la conformité réglementaire indispensable pour les biens immobiliers situés à Cannes.`,
    client: "Claire Morel",
    price: "1 690 €",
    category: "Remise aux normes",
    date: "28 février 2024",
    location: "Centre-ville, Cannes",
  },
  {
    slug: 'Remplacement-et-modernisation',
    image: "/images/Remplacement-et-modernisation.webp",
    title: "Modernisation et rénovation de tableau électrique à Cannes",
    subtitle: "Remplacement des tableaux anciens et mise à jour électrique",
    description: `Le client basé à Mandelieu-la-Napoule, près de Cannes, nous a demandé de remplacer un tableau électrique vieux de plus de 25 ans. Nous avons installé un tableau moderne avec modules modulaires, interrupteurs différentiels et disjoncteurs dernière génération. Cette modernisation électrique à Cannes assure une sécurité renforcée et un système évolutif, idéal pour les futures rénovations électriques.`,
    client: "Jean Lefèvre",
    price: "1 290 €",
    category: "Rénovation & modernisation",
    date: "9 mars 2024",
    location: "Mandelieu-la-Napoule, Cannes",
  },
  {
    slug: 'Installation-LED',
    image: "/images/eclairage-exterieur-cannes.webp",
    title: "Éclairage extérieur LED à Cannes",
    subtitle: "Installation LED et économies d’énergie pour jardin et piscine",
    description: `Nous avons conçu et installé un système d’éclairage extérieur LED autour d’une villa avec jardin et piscine à Cannes. Le projet comprend spots encastrés, lampes murales basse consommation, détecteurs de mouvement et pilotage automatique via horloge crépusculaire. Cette installation LED à Cannes améliore la sécurité nocturne et valorise les espaces extérieurs tout en réduisant la consommation d’énergie.`,
    client: "Sophie Lambert",
    price: "890 €",
    category: "Éclairage extérieur",
    date: "15 avril 2024",
    location: "Quartier Luynes, Cannes",
  },
  {
    slug: 'Panne-generale',
    image: "/images/Panne-générale.webp",
    title: "Dépannage électrique en urgence à Cannes",
    subtitle: "Intervention rapide pour panne générale et disjoncteur HS",
    description: `Intervention urgente un dimanche soir suite à une panne générale dans un appartement à Cannes Ouest. Le disjoncteur principal défectueux a été remplacé immédiatement, permettant un rétablissement du courant en moins de 2 heures. Nous avons sécurisé le tableau électrique avec des disjoncteurs neufs pour éviter toute récidive. Service dépannage électrique fiable et rapide à Cannes, disponible 7j/7 pour vos urgences.`,
    client: "Nicolas Petit",
    price: "290 €",
    category: "Dépannage urgence",
    date: "6 mai 2024",
    location: "Pont de l’Arc, Cannes",
  },
  {
    slug: 'Installation-de-prises-et-interrupteurs',
    image: "/images/Installation-de-prises-et-interrupteurs.webp",
    title: "Installation de prises et interrupteurs à Cannes",
    subtitle: "Travaux rapides et soignés dans espace coworking",
    description: `Dans un espace de coworking en rénovation à Cannes, nous avons installé une vingtaine de prises électriques, interrupteurs modernes et chargeurs USB intégrés. Ce travail électrique assure une distribution optimale de l’électricité et une finition esthétique irréprochable. Réalisé en une journée, ce chantier à Cannes n’a pas perturbé les autres corps de métier.`,
    client: "Émilie Garnier",
    price: "590 €",
    category: "Installation électrique",
    date: "23 juin 2024",
    location: "Quartier Jas-de-Bouffan, Cannes",
  },
];
